# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

api_register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: [POST]

api_login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: [POST]

api_logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout
    methods: [POST]

# Keep security logout route
_security_logout:
    resource: security.route_loader.logout
    type: service
